### PR TITLE
Cleanup image handling

### PR DESCRIPTION
**Pull request by eecharlie**
Some small adjustments to makefile & git tracking for processing of .png's

### CODE REVIEW

**Comment by aequitas** [comment]
Thanks for the PR but I'm not going to merge this. There is a bug in the later versions of imagemagick which cause invalid images. Hence the check to prevent running with the wrong version: 

https://github.com/aequitas/macos-menubar-wireguard/blob/69097123f8f35f29611cc9e329d639ab4914361e/Makefile#L161

Also the generated images are included into git on purpose so they don't need to be regenerated.

So the question then is, why do the images 'want' to regenerate? I tried to setup the Makefile in such a way that the images only want to regenerate when needed (ie: the source changes). And the source for the images is included in git as well so this should not happen. Either Make does not work as expected on your environment, the source file (`Misc/wireguard.svg`) in your repo is newer then the generated image files, which trigger a regenerate or the generated files where removed.

**Comment by eecharlie** [comment]
This is frustrating. Of course, your code and comment are not consistent: you screen to require 7.0.8-9, but your comment only says that versions 8-15 and 8-16 have bugs. The current version, which is the only one supported for auto-install by a Brewfile, is 7.0.8-21. Is there really a bug for *all* versions after 7.0.8-9?

Why is regenerating images during build such a penalty, but many meaningless binary files being stored in the repo is not?

**Comment by aequitas** [comment]
I understand the frustration but this was the best solution I ended up with. Since Brewfiles don't allow pinning versions. At the time I wrote this 7.0.8-21 wasn't there yet, so it would be false information to say it is not supported.

But since the images you included in your PR show the same problems with infill (eg: https://github.com/aequitas/macos-menubar-wireguard/pull/19/files?short_path=9bdbf76#diff-9bdbf76fbeb54a6b97b6d41d26c51bff) I think we can safely say it is not fixed yet.

I'm including the images in the just to prevent this specific problem. Since these images can't be reproduced reliably. The stuff in the makefile is just so I can regenerate the whole bunch easily when I want to change something (and I like automating stuff with make). And if you where to pick the project up in Xcode, straight from git, without running make, it would not build properly. So another reason to keep the images in.

But the whole image generation process is not a step that you should have to perform to build your own version of this app. Like I said before, the Makefile should be smart enough to not want to rebuild the images, unless you removed them or the source changed. So to solve your problem we should be looking at why that happens. Did you run `make mrproper` at any point? Or changed any of the source files?

**Comment by eecharlie** [comment]
You can use a script with a reference to a git commit to force a version: [build-setup.sh](https://github.com/eecharlie/macos-menubar-wireguard/blob/b92f552bb8e4e2c2b594f3994cb45a3ab67ea453/Misc/build-setup.sh)

When I just tried a fresh clone & make using your repo, the image building is called by make but didn't trigger file modifications to git. I did not call `make mrproper`; and I assume by source files you mean svg files not code

So, what is the best practice for someone to clone your repo and build & test successfully? There already must be some command-line work to ensure dependencies are set up, and the xcode project file must be updated with developer credentials, easiest to do within XCode. Your readme says that integration & distribution testing can only be done using make. You're using Travis-CI configured for xcode, which means automated testing is restricted to tests defined in XCode.

So, given that it's not possible to do all build tasks either within XCode or at cli, automating and doing as much as possible in the shell doesn't seem like a terrible idea, and probably using the makefile for some if not all Travis-CI testing. If building the image files is part of a standard build script and is reproducible by others who clone the repo, it makes it possible for others to observe and debug problems with Imagemagick.

**Comment by eecharlie** [comment]
Also, Makefile integration testing is not working for me:
```
$ make prep-integration
make: stat: /etc/wireguard/test-localhost.conf: Permission denied
sudo cp IntegrationTests/test-localhost.conf /etc/wireguard/test-localhost.conf
make: stat: /etc/wireguard/test-localhost.conf: Permission denied```

**Comment by aequitas** [comment]
Both mentioned problems are now solved in https://github.com/aequitas/macos-menubar-wireguard/commit/b0b8f158139103ad1758fc60dd5e064f76b36e74. I've included the intermediate images instead of leaving them in $TMPDIR so they won't trigger a rebuild. Permissions for the /etc/wireguard directory are now also set when creating the fixture file.

As for testing scripts. Travis can't do the UI tests or integration tests due to limitations of the Travis environment. Thats why those tests are done using make. Only code quality and simple unit tests are done in Travis. Its not a complete test, but better than nothing in this case.

**Pull request closed without merging**
